---
title: "R Exam"
author: "Student"
date: "8/16/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Q4 Market Segmentation

```{r market data preprocessing, echo=FALSE, message = FALSE, warning=FALSE}
library(ggplot2)
library(reshape2)

social_marketing = read.csv("social_marketing.csv")
summary(social_marketing)

```

```{r market data analysis1, echo=FALSE, message = FALSE, warning=FALSE}
#checking null values
null_Check <- t(as.data.frame(lapply(social_marketing,function(x) {length(which(is.na(x)))})))

#checking nonzero values
count_check <- t(as.data.frame(lapply(social_marketing,function(x) {length(which(x!=0))})))

#density plots
par(mfrow=c(2,2))
for(i in 2:ncol(social_marketing)){
  boxplot(social_marketing[,i], xlab = colnames(social_marketing)[i])
}

```

```{r market data analysis2, echo=FALSE, message = FALSE, warning=FALSE}
cordata <- cor(social_marketing[,-1])
melted_cordata <- melt(cordata)
ggplot(data = melted_cordata, aes(x=Var1, y=Var2, fill=value)) + 
geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1,1), space = "Lab", 
                       name="Pearson\nCorrelation") +
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                   size = 12, hjust = 1))+
  coord_fixed()

cordata2 <- melted_cordata[melted_cordata$Var1 != melted_cordata$Var2 & melted_cordata$value>0.6 , ]

```

```{r market data modelling, echo=FALSE, message = FALSE, warning=FALSE}
##pca and hclust
pca_data <- prcomp(social_marketing[,-1])
summary(pca_data)

pr_var <-  pca_data$sdev ^ 2
pve <- pr_var / sum(pr_var)
plot(pve, xlab = "Principal Components", ylab = "Proportion of Variance Explained", ylim = c(0,1), type = 'b')

plot(cumsum(pve), xlab = "Principal Component", ylab = "Cumulative 
     Proportion of Variance Explained", ylim =c(0,1), type = 'b')

rot_loading <- varimax(pca_data$rotation[, 1:7])
rot_loading

library(FactoMineR)
library(factoextra)
res.pca <- PCA(social_marketing[,-1], ncp = 7, graph = FALSE)
res.hcpc <- HCPC(res.pca, graph = FALSE)
fviz_dend(res.hcpc, 
          cex = 0.7,                     # Label size
          palette = "jco",               # Color palette see ?ggpubr::ggpar
          rect = TRUE, rect_fill = TRUE, # Add rectangle around groups
          rect_border = "jco",           # Rectangle color
          labels_track_height = 0.8      # Augment the room for labels
)


```

# Q6 Association Mining Rules

```{r preprocessing, echo=FALSE, message = FALSE, warning=FALSE}
library(arules)
library(arulesViz)
library(tidyverse)
library(RColorBrewer)

##loading the dataset to list of transactions
groceries <- read.transactions("groceries.txt", format = "basket", sep = ",", rm.duplicates = T)
summary(groceries)
itemFrequencyPlot(groceries,topN=20,col=brewer.pal(8,'Pastel2'),main='Relative Item Frequency Plot',
                  type="absolute", ylab="Item Frequency (Relative)") 

```

However, I can call the same object in another chunk.

```{r modelling, echo=FALSE, message = FALSE, warning=FALSE}
#modelling
arulesgroceries <- apriori(groceries, parameter = list(support = 0.002, confidence = 0.01, maxlen = 40))
#inspect(arulesgroceries)

arulesgroceries <- apriori(groceries, parameter = list(support = 0.002, confidence = 0.1, maxlen = 10))
#inspect(arulesgroceries)

arulesgroceries <- apriori(groceries, parameter = list(support = 0.002, confidence = 0.3, maxlen = 10))
inspect(arulesgroceries)

```


```{r plots & visualizations, echo=FALSE, message = FALSE, warning=FALSE}

plot(arulesgroceries)

inspect(subset(arulesgroceries, subset = lift>5))

plot(head(sort(arulesgroceries, by="support"), 20),
     method="graph", control=list(cex=.9))

plot(head(sort(arulesgroceries, by="lift"), 20),
     method="graph", control=list(cex=.9))
```

